### ISSUE TITLE
Flake8 GitlabCodeClimateReporter format

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1114]
In GitLab by @syed_ansar on Dec 1, 2020, 02:41

Hi, how do I use flake8 to report code quality issues to the gitlab code climate reporter please. Here is a pylint configuration to help illustrate how one can have pylint warnings displayed to gitlab's code quality widget in merge request review; is there a similar feature for flake8. Any help on using flake8 also will be much appreciated.
```
lint:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script:
    - pip install pylint_gitlab
  script:
    - pylint --exit-zero --disable C0103,C0114 --output-format=pylint_gitlab.GitlabCodeClimateReporter $(find -type f -name "*.py" ! -path "**/.venv/**") > codeclimate.json
  artifacts:
    paths:
      - public
    reports:
      codequality: codeclimate.json
    when: always
```
