### ISSUE TITLE
Use setup.cfg configuration with pre-commit?

### ISSUE THREAD

**Issue by ahgraber** [PyCQA/flake8#1483]
*Please describe how you installed Flake8*

```
conda install -n envname flake8
```

**Note**: Some *nix distributions patch Flake8 arbitrarily to accommodate incompatible software versions. If you're on one of those distributions, your issue may be closed and you will be asked to open an issue with your distribution package maintainers instead.

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.0",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    }
  ],
  "version": "4.0.1"
}

```

*Please describe the problem or feature*

I have flake8 configured in `setup.cfg` at the root of my project directory.  It appears that this configuration is not read/respected when I run flake8 using pre-commit.  Is there a way to set flake8 to register it's configuration with pre-commit?  Or is this an issue on the pre-commit side?

I can run `flake8 .` from the root of the project directory and it returns clean, but running `pre-commit run --all-files` identifies violations that were ignored in `setup.cfg`, especially around per-file-ignores

setup.cfg:
```
[flake8]
max-complexity = 18
max-line-length = 119
select = B,C,E,F,N,W,T4,B9,C4
extend-ignore = E203, E265, E266, E501, W503, F401, F403, F405, F541
extend-exclude = .ipynb_checkpoints,.tox,.eggs,*.egg-info,ci/templates,build,dist,docs/conf.py
per-file-ignores =
    src/package/foo.py: N806
    src/package/bar.py: N806
```

pre-commit-config.yaml
```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1" # v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2" # 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-colors
          - flake8-comprehensions
          - flake8-isort
          - pep8-naming
```
