### ISSUE TITLE
Config file .flake8 not exist when running github actions

### ISSUE THREAD

**Issue by luissian** [PyCQA/flake8#1647]
### how did you install flake8?

```console
jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.x
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8==4.0.1
      - name: Run flake8
        uses: suo/flake8-github-action@v1
        with:
          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### unmodified output of `flake8 --bug-report`

```json
platform: git hub
```

### describe the problem

# Description of the issue
I have been using flake8 to run during the github  actions. Configuration code is described above in how install flake8.

It was great until the new release 5.0.x was released on the 30th of July. 
Starting from this release flake8 always fails because is trying to get the configuration from the runner server, which of course does not exist. 

#### what  happen
```
There was a critical error during execution of Flake8:
The specified config file does not exist: /home/runner/work/<my_repository>/.flake8
Error: The process 'flake8' failed with exit code 1

**Comment by asottile** [comment]
without seeing the commandline that's being run or the bug report output or your repository I can't help you

the output you're suggesting also looks impossible -- you're pinning 4.0.1 and the error message is from 5.0.x

there's a relevant entry from the changelog which I suspect is what you're encountering -- but I don't see that being possible from the little information you've given me (especially as [that action doesn't pass any configuration arguments](https://github.com/suo/flake8-github-action/blob/3e87882219642e01aa8a6bbd03b4b0adb8542c2a/src/main.ts#L17))

**Comment by luissian** [comment]
Yes , you are right sorry the error I get when not indicating the release, which by default get the latest at present 5.0.2 .

I do not execute myself the flake in any terminal, but as I mention, I use Flake8 as part of the git workflows. 
below the full .yml file that I use for running the workflows action.
I hope if help you , if not tell me what you need for ,
Thanks for your really fast response

------
name: python_lint

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.x
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACTIONS }}

**Comment by asottile** [comment]
so sub out the action with just `run: flake8 --bug-report && flake8 --exit-code` shouldn't be too hard

**Comment by luissian** [comment]
same result as before 

Run flake8 --bug-report && flake8 --exit-code
##[debug]/usr/bin/bash -e /home/runner/work/_temp/b48edf99-4749-4d33-b122-53eab29ed9a9.sh
There was a critical error during execution of Flake8:
The specified config file does not exist: /home/runner/work/relecov-platform/relecov-platform/.flake8
Error: Process completed with exit code 1.
##[debug]Finishing: Run flake8

**Comment by asottile** [comment]
[surround your code with backticks so it's formatted nicely](https://youtu.be/1UodxuXj5Ao)

ok you could have led with your repository and then I wouldn't have been guessing at your problem: https://github.com/BU-ISCIII/relecov-platform

you've got an invalid `ini` file -- but that doesn't explain why it's asking about an unrelated configuration file: https://github.com/BU-ISCIII/relecov-platform/blob/f7057fa1cea2ad412443991a776fb633bf18b04c/tox.ini#L4

**Comment by luissian** [comment]
yes Better this way ;-)

```
name: python_lint

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.x
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 --bug-report && flake8 --exit-code

```
Check better on my repo 
https://github.com/luissian/relecov-platform/tree/develop
I can make changes for testing. 
At BU-ISCIII only I can do a Pull Request.
