### ISSUE TITLE
[5.0.4] Incompatible with Sphinx 5.1.1 due to `importlib-metadata` constraint

### ISSUE THREAD

**Issue by demberto** [PyCQA/flake8#1686]
### how did you install flake8?

```console
poetry add flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.7",
    "system": "Windows"
  },
  "plugins": [
    {
      "plugin": "flake8-docstrings",
      "version": "1.6.0"
    },
    {
      "plugin": "flake8-typing-imports",
      "version": "1.13.0"
    },
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pep8-naming",
      "version": "0.13.2"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.1"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.4"
}
```

#### Dependencies

```toml
[tool.poetry.group.dev.dependencies]
Sphinx = "^5.1.1"
towncrier = "^22.8.0"
black = "^22.8.0"
isort = "^5.10.1"
flake8 = "^5.0.4"
tox = "^3.26.0"
pytest = "^7.1.3"
```

#### Output

```
Because no versions of flake8 match >5.0.4,<6.0.0
 and flake8 (5.0.4) depends on importlib-metadata (>=1.1.0,<4.3), flake8 (>=5.0.4,<6.0.0) requires importlib-metadata (>=1.1.0,<4.3).
And because sphinx (5.1.1) depends on importlib-metadata (>=4.4)
 and no versions of sphinx match >5.1.1,<6.0.0, flake8 (>=5.0.4,<6.0.0) is incompatible with Sphinx (>=5.1.1,<6.0.0).
So, because flpexport depends on both Sphinx (^5.1.1) and flake8 (^5.0.4), version solving failed.
```
