### ISSUE TITLE
Misconfigured default branch on GitLab

### ISSUE THREAD

**Issue by pawel-ch** [PyCQA/flake8#1736]
### how did you install flake8?

```console
Irrelevant
```

### unmodified output of `flake8 --bug-report`

```json
Irrelevant
```

#### what I expected to happen

Hi, I just wanted to let you know, that your migration from `master` to `main` as default branch in GitLab is incomplete which causes issue with `pre-commit autoupdate`. Because of that **it will never automatically upgrade beyond 3.9.2** (last version released on `master` branch) and the command will **always downgrade to 3.9.2 if you do the upgrade manually**.

You can see that `master` is still default [here](https://gitlab.com/pycqa/flake8/-/branches/stale).

FYI, `pre-commit` does something like this to check the latest Flake8 version:

```console
$ git init
$ git remote add origin https://gitlab.com/pycqa/flake8
$ git fetch origin HEAD --tags
$ git describe FETCH_HEAD --tags --abbrev=0
```

#### sample pre-commit configuration

```yaml
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies:
          - flake8-isort==5.0.0
```

#### commands ran

```console
$ pre-commit autoupdate
```

#### solution

Just kindly go to https://gitlab.com/pycqa/flake8/-/settings/repository, expand **Default branch** and change it to **main**.

#### workaround

A slightly different `pre-commit` configuration:

```yaml
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies:
          - flake8-isort==5.0.0
```
