### ISSUE TITLE
Provide configuration of exclusions via a list of exclusion rules that support per-line regular expressions, regular expressions against linter text, and by path

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [PyCQA/flake8#1815]
### describe the request

flake8 allows you to disable certain rules in some files using [per-file-ignores](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-per-file-ignores).  This still has limited flexibility in that we can't disable certain rules for certain lines, e.g. matching a regular expression.

Compare with another similar linting tool for Golang that I regularly use, golangci-lint.  It provides an [issues configuration](https://golangci-lint.run/usage/configuration/#issues-configuration) that is very flexible for defining exclusions.  We can define various matching rules for exclusions (path, source code text/regular expression, linter output text/regular expression) in order to very flexibly exclude linter violations.

```yaml
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    # Exclude known linters from partially hard-vendored code,
    # which is impossible to exclude via `nolint` comments.
    # `/` will be replaced by current OS file path separator to properly work on Windows.
    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec
    # Exclude some `staticcheck` messages.
    - linters:
        - staticcheck
      text: "SA9003:"
    # Exclude `lll` issues for long lines with `go:generate`.
    - linters:
        - lll
      source: "^//go:generate "
```

Here is an example that I set up to ignore long lines based on a pattern I defined:
```yaml
  exclude-rules:
    # exclude long lines matching certain patterns:
    # - go:generate directives: there's no way to wrap these across multiple lines
    # - URLs: these really hurt readability to try to wrap
    # - github.com: a heuristic to exclude long import lines
    - linters:
        - revive
      text: "line-length-limit"  # match any linter error with this text in it (it's the name of the lint rule that was violated)
      # nice little regular expression to match the source code
      source: '^\s*//go:generate |https?://|github\.com'
```

I would like to accomplish something similar with flake8.  The pycodestyle plugin has a special case to ignore long URLs, but the rule is too rigid for my taste and I'd like to define a different pattern:
https://github.com/PyCQA/pycodestyle/blob/b22b672a1a53f1ef35c4f4689c674d66a24138ed/pycodestyle.py#L278-L285
Rather than have some special configurable thing with pycodestyle, I think it would be best if there was a general-purpose framework for ignoring issues similar to how other linter tools like golangci-lint can do.
