### ISSUE TITLE
pre-commit cache contains tests folder

### ISSUE THREAD

**Issue by shepilov-vladislav** [PyCQA/flake8#1917]
### how did you install flake8?

```console
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        types: [python]
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.11.7",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.11.1"
    },
    {
      "plugin": "pyflakes",
      "version": "3.2.0"
    }
  ],
  "version": "7.0.0"
}
```

#### what I expected to happen
unit tests should not break on CI
...

#### Gitlab CI Config

```yaml
stages:
- lint
- test

linters:
  image: python:3.11.7
  stage: lint
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  before_script:
    - pip install --upgrade pre-commit
  script:
    - pre-commit run --all-files
  cache:
    paths:
      - ${PRE_COMMIT_HOME}

tests:
  image: python:3.11.7
  stage: test
  cache:
    paths:
      - .cache/pip
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest --cov
```

#### commands ran

```console
...
=========================== short test summary info ============================
FAILED .cache/pre-commit/repo3wf0f0w3/tests/unit/test_file_processor.py::test_processor_split_line - AttributeError: 'FileProcessor' object has no attribute 'multiline_string'
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
======================== 1 failed, 205 passed in 6.05s =========================
...
```

This happens because the flake8 test directory gets into the pre-commit cache, while the CI cache is in `./.cache/pre-commit/...` and the pytest runner tries to run this test too. I understand that I can change the location of the cache folder, but still it seems to me that this behavior of pre-commit for flake8 is strange and a better solution would be to exclude the tests directory from pre-commit.
